
name: "Dev Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 78162dcb-f043-40a8-a18d-21ccbb2ffa09
          tenant-id: 89fd6166-81c8-4b8b-9b7c-12306da8371e
          subscription-id: 1a3d832a-d69d-49ee-b438-ba5fd2fc00bf
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 78162dcb-f043-40a8-a18d-21ccbb2ffa09
          tenant-id: 89fd6166-81c8-4b8b-9b7c-12306da8371e
          subscription-id: 1a3d832a-d69d-49ee-b438-ba5fd2fc00bf   
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/dev              
          
